// app/layout.tsx
import './globals.css'
import { ReactNode } from 'react'
import Navbar from '@/components/navbar'

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
